### PR TITLE
Parameter xsd and annotation

### PR DESCRIPTION
**Pull request by ScienJus**
see #309 and alipay/sofa-rpc-boot-projects#136.

### CODE REVIEW

**Comment by straybirdzls** [comment]
@ScienJus hello, can you add some cases for the xsd change, currently we do not have xsd cases in this project, but we write some cases in internal project, an example is as below:

```java

@Test
public void test() throws Exception {
        loadXml("XX.xml");
}

private void loadXml(String xml) throws Exception {
        DocumentLoader documentLoader = new DefaultDocumentLoader();
        documentLoader.loadDocument(new InputSource(this.getClass().getClassLoader()
            .getResourceAsStream(xml)), new DelegatingEntityResolver(this.getClass()
            .getClassLoader()), new DefaultErrorHandler(),
            XmlValidationModeDetector.VALIDATION_XSD, true);
    }
```

Keep us noticed no matter whether you are convenient or not 😊.

**Comment by ScienJus** [comment]
@straybirdzls just added a sample, please take a look.

Do you need more cases? (such as a failed case?)

**Comment by straybirdzls** [comment]
@ScienJus great👍 I think one failed case will be better and enough，eg: `sofa:parameter` with no key or no value.

**Comment by ScienJus** [comment]
@straybirdzls done.

Note: when this PR is merged, we need to upgrade the sofa-boot version in the sofa-rpc-boot-projects to implement the part of sofa-rpc-boot-projects.

**Comment by QilongZhang** [comment]
> @straybirdzls done.
> 
> Note: when this PR is merged, we need to upgrade the sofa-boot version in the sofa-rpc-boot-projects to implement the part of sofa-rpc-boot-projects.

I have deployed  2.6.0-SNAPSHOT to maven snapshot repo, you can continue your work. thx.

**Pull request merged**
